name: Lint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run linter
        run: mdl -r ~MD033,~MD007,~MD013,~MD022,~MD036,~MD029 content/**/*.md
